word_themes = {
    "① 사람·관계": [
        {"word": "person", "meaning": "사람"},
        {"word": "man", "meaning": "남자"},
        {"word": "woman", "meaning": "여자"},
        {"word": "child", "meaning": "아이"},
        {"word": "baby", "meaning": "아기"},
        {"word": "boy", "meaning": "소년"},
        {"word": "girl", "meaning": "소녀"},
        {"word": "friend", "meaning": "친구"},
        {"word": "family", "meaning": "가족"},
        {"word": "parent", "meaning": "부모"},
        {"word": "father", "meaning": "아버지"},
        {"word": "mother", "meaning": "어머니"},
        {"word": "brother", "meaning": "형제, 남자 형제"},
        {"word": "sister", "meaning": "자매, 여자 형제"},
        {"word": "son", "meaning": "아들"},
        {"word": "daughter", "meaning": "딸"},
        {"word": "teacher", "meaning": "선생님"},
        {"word": "student", "meaning": "학생"},
        {"word": "classmate", "meaning": "반 친구"},
        {"word": "neighbor", "meaning": "이웃"},
        {"word": "customer", "meaning": "손님, 고객"},
        {"word": "worker", "meaning": "노동자, 직원"},
        {"word": "driver", "meaning": "운전자"},
        {"word": "doctor", "meaning": "의사"},
        {"word": "nurse", "meaning": "간호사"},
        {"word": "police officer", "meaning": "경찰관"},
        {"word": "owner", "meaning": "주인"},
        {"word": "guest", "meaning": "손님"},
        {"word": "team", "meaning": "팀, 무리"},
        {"word": "member", "meaning": "구성원"},
    ],

    "② 학교·교실": [
        {"word": "school", "meaning": "학교"},
        {"word": "class", "meaning": "수업, 학급"},
        {"word": "classroom", "meaning": "교실"},
        {"word": "lesson", "meaning": "수업, 과"},
        {"word": "homework", "meaning": "숙제"},
        {"word": "test", "meaning": "시험"},
        {"word": "exam", "meaning": "시험"},
        {"word": "quiz", "meaning": "퀴즈, 간단한 시험"},
        {"word": "question", "meaning": "질문, 문제"},
        {"word": "answer", "meaning": "대답, 정답"},
        {"word": "book", "meaning": "책"},
        {"word": "notebook", "meaning": "공책"},
        {"word": "paper", "meaning": "종이, 보고서"},
        {"word": "pen", "meaning": "펜"},
        {"word": "pencil", "meaning": "연필"},
        {"word": "desk", "meaning": "책상"},
        {"word": "chair", "meaning": "의자"},
        {"word": "board", "meaning": "칠판, 게시판"},
        {"word": "page", "meaning": "쪽, 페이지"},
        {"word": "word", "meaning": "단어, 말"},
        {"word": "sentence", "meaning": "문장"},
        {"word": "story", "meaning": "이야기"},
        {"word": "language", "meaning": "언어"},
        {"word": "English", "meaning": "영어"},
        {"word": "Korean", "meaning": "한국어"},
        {"word": "grade", "meaning": "성적, 학년"},
        {"word": "score", "meaning": "점수"},
        {"word": "rule", "meaning": "규칙"},
        {"word": "practice", "meaning": "연습하다, 연습"},
        {"word": "study", "meaning": "공부하다"},
    ],

    "③ 기본 동작 동사": [
        {"word": "go", "meaning": "가다"},
        {"word": "come", "meaning": "오다"},
        {"word": "walk", "meaning": "걷다"},
        {"word": "run", "meaning": "달리다"},
        {"word": "sit", "meaning": "앉다"},
        {"word": "stand", "meaning": "서다"},
        {"word": "stop", "meaning": "멈추다"},
        {"word": "start", "meaning": "시작하다"},
        {"word": "open", "meaning": "열다"},
        {"word": "close", "meaning": "닫다"},
        {"word": "make", "meaning": "만들다"},
        {"word": "do", "meaning": "하다"},
        {"word": "have", "meaning": "가지다, 먹다"},
        {"word": "get", "meaning": "얻다, 받다, 되다"},
        {"word": "take", "meaning": "가져가다, 타다"},
        {"word": "give", "meaning": "주다"},
        {"word": "put", "meaning": "놓다, 두다"},
        {"word": "bring", "meaning": "가져오다"},
        {"word": "use", "meaning": "사용하다"},
        {"word": "find", "meaning": "찾다"},
        {"word": "keep", "meaning": "유지하다, 보관하다"},
        {"word": "leave", "meaning": "떠나다, 남기다"},
        {"word": "move", "meaning": "움직이다, 이사하다"},
        {"word": "turn", "meaning": "돌다, 돌리다"},
        {"word": "wait", "meaning": "기다리다"},
        {"word": "help", "meaning": "돕다"},
        {"word": "try", "meaning": "시도하다"},
        {"word": "need", "meaning": "필요하다"},
        {"word": "want", "meaning": "원하다"},
        {"word": "like", "meaning": "좋아하다"},
    ],
}
